language: node_js
node_js:
  - lts/*
script: yarn build
deploy:
  - provider: firebase
    on:
      branch: master
    project: vgbc-tracker
    skip_cleanup: true
    token:
      secure: BP5HPESh4TVyhGwHUZ5Ni/3N15qt1mILHTeDUkpdvoEX9KlYmEcoSc5sU9zDOpKTt/i4ncK9y5ixQs4l9LWg4N0swqmSEbzKRqNMUN6ALv+FNKmATTUvId1tK6N76BX7WlJqhynDv7GGqy00uQTVXVzW8Mqt9Hfqv/BRB+pvfigPCneekjXPbrCv8g2cuMNVuYX/q+54BStetRl/2AZVf2Y67LA5lxo7wYA4WUBv8r0jDY7veMyixh6sWNDHYSVZEEWoeKh3bkf7jmzauT+cArQPKlEuWNslFpAfjRfOEfQlkx06Sdn5lQVHrNlpR0Wz7knEWCNAgQcDyhAEZ/admUbTB9SgP7k0LD82WGmijrNZ72KftCYBBo7MTQgvI5Ag6Jh4ngBlwGJvG+TaFRlPkW0KTI2/gb6PwosIXiX1du6BuloFo+9W9hzIlHErlTd/gNnoTkLaO9qc2MHNBJ8gJH0H0TtRYORqDKcR+tFvXJVI6wlGcKNKoQKMTwIDO0sagkJUqIOLWex9lJ1/z0Og8kLtcK0NSL0+EZz3SXFrcEqyMd7WKdVgWntbWT281kryK46xn2PftGd9EXJcO5lCVYyD/0gJw+AIyEk28adGEAPMdeLRlg+ui9mTxCIAysc/I2IWzDG4oxHk91yo9mlUFTmE+5u20922Igy6jnCwc6o=
  - provider: firebase
    on:
      branch: develop
    project: vgbc-tracker-dev
    skip_cleanup: true
    token:
      secure: mtGr5HuTEso9cok55e2jQ3YFEjOisG/SXOtGxtC9X9kzomIo1rfENjMwVMFXrCNFqfG4bF+9TSQpblcqdNJQtaSFtcBNELlbBGBzVwLLY26cVQdEkL7zFdd2hOSjIPPsc/jsILA2vrdbNYTVQWEQyyjC7uSRhmBrnbVXD6y3BN1yts1om1V6WobEJIq1k7axBaU9IXYFCTAucOwuyJes3MVQ0lnAdglLZXaFHbORrKTpVOu9bB2Ur1Dmhqlil9Lk+60EzRyuA+nPkrRMX+AqOAeDBoL3UpoyxLN63AVpvJ/t41NX6gEtrbM8/ju+5HffN5UeogcFh/8acltGD7oPLF+HE3VfurGYCrHtFySFzFBt/+01BfJqxYmueSgkm+oMTL1soeKGGi/PFgfH+L0eiRWE36pImQ1nuy3obsq99JU6kloP278tLjhmFuKq/IZZZEE2ByCblvk9vlXzqrjUW2bHdUhIcWed/aJg39yYXDWm1XdlVkZt7Imr4LvY59+RvQXDIu0ZXFh5Kt5oXIU1FhUkAJhOZ2RMk2kvzbMKElNgX0TE1DNkTTsOHHKpJWVAwQeYNBKxuvvdJxGuIcLWP4wne5TB3BhOQMjBnlBI9xKhdYmm/TVzoair12Cf3SJSqEuInRWtpBIfISCfLeDTTXn14GvO7j8HWo4qZsbD8V4=
before_deploy:
  - yarn install --cwd ./functions
