language: node_js
node_js:
  - lts/*
script: yarn build
deploy:
  provider: firebase
  on:
    branch: master
  token:
    secure: "Qlf7wTtLPQEUf8g1h9lXIPSuxBKOabSvoJIYuPEvpSwnIOI+3wM1ETNiiieious9WsWo4pqxNpeOOLwGDOcfpjWXpPonhDQ7Px1Ob0BMa63PG7oNzFwi1c+aJtaw5+Do3ZxLNL9BJxP89pkUJSAkefalL3WQ8OQ/HNeNgYFp9GSPjLzG5gHeahS7O6ABMhvTEd75BoAGK2UjE9TPHBN88YgzwjRZLvIOdnwcAvujwNQJrX2nhvLgxtL/yxarNggkoLveGMHUEM6B5S4iY8LJVOxW4a9378CdaIDUY8LWvbsigbxwqGbgro08iSY+In76IGp1JycpJjuSDRIV2b4Huir6tb4YBBIlfDsH0R5+7DxJ4y9UiflkPGhj/I3/X6pqRz5DRtJUCpCj+E6eFd1YKygxVoDOp2k4LGDdiclbYGcqGQZHIrHCyzgHeMw+WoecO6X6nPmN6VhIgOUSolkhDiKIczuzhnZa8rM/rLlxB3z1uMew0ZbG2i3pj9rF9Gg2ogviUOECuLFunUOBdrhlnc6J7KIx3UKgGyWW8D/DacdVnJNwK4KzGVR52Gkh2cf81XmUJBg+4JNtof6HeIXCj1RpG/OmmnBMIj+rbXdPa+6zR3tIh2YzUGIAkftjDyeQWwSYaVf3UJEwOWjdaV4eqABNEmAjLH9xmPC0twzYeys="
  project: 'vgbc-tracker'
