language: node_js
node_js:
  - lts/*
script: yarn build
deploy:
  - provider: firebase
    on:
      branch: master
    project: vgbc-tracker
    skip_cleanup: true
    token:
      secure: QhGLgOsbZFOK38RRNjfA82eaPY9nO3GpmUp2ZsNCuVcnRH8vAce98Gw+zjGFXOATv3jREnO9zm1b/YnYHqfd6pL/hj5aZog0ROwJwxgVcYcI8LM/3VdWHrkWZg9E4QOOiWlJILGaaEN/GS2kms2n/mw1W6Lqu3GiDP78kglPsVOz3/+kmDRtoQLv47nuz++7Qfqj+YesYjrQayBv9T9K+v56ObPympRubOZxcOkfDw5lMK5Xc6QN1K3gMJewRVjG7Ht5W3ppxUJjhBVtbQvb+cZ5d75IWBlzzLPgvXgcmsl4TjW2lhnouhOwMH57YMIdAW++otpnCQ4WiSaHaABbbz00eK2YSaRCGXnq0Y2td75HJ2zT/275XoK4q1k6nxvFi5Ahr4fpjrR1T8bWY2iDQmQ2HFu1fM4zBD6pJKgQoD9xt/fBD5/MC7v+WJxqIFdFaCfV5CRLzN7fnSoNMHjs+lqSDtaub8f9zyU/qrmxpgX+Nnw89se5BvlXz1EW2LeEChegYV8n5+F9sfmkNlsrVQW5rrDXUC/oeZZKKdT6RH24nyBC1h8VUR9m68ghiVHV5J+shyAY9fmCzgEpjvcriLdZ8n0vK7VUEqaAQ8CpSSGs6y1HdX3gUTDZFQFTZhOlnxhKs4NzaMZPJlq8rGZDzvmrsy1l/VMkBBCXtMR7gvQ=
  - provider: firebase
    on:
      branch: develop
    project: vgbc-tracker-dev
    skip_cleanup: true
    token:
      secure: i2JhHhaLJylSeR0o/VNw6RoqX+JjtmiZSyX6gYvM7nKxerHY/S0nRAp2R8CqCEwdT+25HVCs5i5Nqdo4KdCbcJ7jhpAIclX6/19cQ63HzGou6zTmtg9MZj+l6iVtMO3N2+kZmsb3SzpApPUQKcbmEFMby/DkpZ5XExoqjpakA87afgMLkN3AX7g1z5dSS0PkCapkHx+kzeyU8f01OwvJ0yaQcB3xGC+1nAZDGu4hkMrQphjNPFNi8NGxlNckJeevCmoFPZnd8xGvnIB2CbSeLTERbL0bvDXg6Yjv3+J+TukIepW2A7T9y4EtWeoco+3S/o5/wVzi80vX1enlAow3TwhFT0BrgzvH9Fe/FiRBnlu5kvRqYTV983fU1I9DFLDxJuaAIW+6mqi25tmVw83QeW6gQ3B+jaT8tFntHXIxwm3kbVS0ySZr6gaEg2WsyD8yF3FswUQMm+mK4bmD+lXq9/08M6TW0XLh9d+puSGJMPm23+/ZIbR86x9OjLONBLUWo6AP3jmmGLNtVw414pxL3goWcq3dwdUPxb3C3lxjOPrCUJcrsEHpHrUgXF6cAfta5a+lli8E5+GAtWweGTXOHqi2/b4CSKg1Ik2JpI/uW6ls1Qh039aCi7XLFl8frChKH4bZXeskCwdnRIy9ybAGfhdxVRvF3aas1JMwTXAyc7A=
before_deploy:
  - yarn install --ignore-engines --cwd ./functions
